[build]
  command = "astro build"
  publish = "dist"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  	paths = [".astro","./node_modules/.astro"]

[[redirects]]
  from = "/badeel"
  to = "https://badeel-masr.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "https://iamnabil.netlify.app"
  to = "https://nabiltharwat.com"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/connect"
  to = "https://nabiltharwat.com/call"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/yt"
  to = "https://www.youtube.com/@NabilTharwat_"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/x"
  to = "https://x.com/kl13nt/"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/gh"
  to = "https://github.com/kl13nt"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/podcast"
  to = "https://theweeklynoob.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/in"
  to = "https://www.linkedin.com/in/i-am-nabil"
  status = 301
  force = true
