[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  	paths = [".next",".npm"]

[[redirects]]
  from = "/badeel"
  to = "https://badeel-masr.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "https://iamnabil.netlify.app"
  to = "https://nabiltharwat.com"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/connect"
  to = "https://nabiltharwat.com/call"
  status = 301
  force = true

[[redirects]]
  from = "https://nabiltharwat.com/sponsor"
  to = "https://github.com/sponsors/KL13NT"
  status = 301
  force = true
